### ISSUE TITLE
Can I use your API to make a little program of WeChat

### ISSUE THREAD

**Issue by trueWangSyutung** [Bistutu/BistuEmpty#4]
我能用你的API做一个微信的小程序吗?
来自 健翔桥 大三
https://gitee.com/syutung/bistu-empty-room

**Comment by trueWangSyutung** [comment]
![Uploading Screenshot_2021-11-30-00-04-40-127_com.tencent.mm.jpg…]()

**Comment by Bistutu** [comment]
## 完全没有问题，我现在的接口规则是这样子的

**https://www.thinkStu.com/校区/校区+月份+天数.json/**

其中校区有：1-小营，2-健翔桥，3-清河，4-沙河
我举几个例子

1. 小营校区11月30日的数据：https://www.thinkStu.com/1/11130.json
2. 健翔桥校区12月1日的数据：https://www.thinkStu.com/2/2121.json

服务器会返回给你一串JSON格式的数据。

### 如果你有兴趣接下来的话，我会协助你进行数据的适配工作，一起为同学们开发程序！

**Comment by trueWangSyutung** [comment]
Thanks , 
我已经提交了一个 beta 版本 给 微信审核

![Screenshot_2021-11-30-09-56-07-830_com.tencent.mm.jpg](https://user-images.githubusercontent.com/67704893/144054528-52854ad7-cb4c-4623-ac26-e571ec502fd0.jpg)
