### ISSUE TITLE
警告

### ISSUE THREAD

**Issue by crazychen0530** [Bistutu/BistuEmpty#5]
大哥我在android stdio里面运行警告很多版本问题，有办法解决吗？

**Comment by crazychen0530** [comment]
It looks like you just edited the `targetSdkVersion` from 33 to 34 in the editor. Be sure to consult the documentation on the behaviors that change as result of this. The Android SDK Upgrade Assistant can help with safely migrating.这个报错怎么解决

**Comment by Bistutu** [comment]
项目是三年之前开发的，现在不维护了，可以问下GPT

**Comment by crazychen0530** [comment]
> 项目是三年之前开发的，现在不维护了，可以问下GPT

好的大哥

**Comment by crazychen0530** [comment]
大佬可否告诉我这个课表的这些数据是存在哪个文件里面，用的是哪个数据库
哇

**Comment by Bistutu** [comment]
后端Spring：https://github.com/Bistutu/BistuEmptySpring
